
development:
  adapter: postgresql
  database: myapp_development
  pool: 5
  username: andrewmadsen
  password:
  timeout: 5000

test:
  adapter: postgresql
  database: myapp_test
  pool: 5
  username: andrewmadsen
  password:
  timeout: 5000
  
production:
  adapter: postgresql
  database: myapp_production
  pool: 5
  username: andrewmadsen
  password:
  timeout: 5000

